### ISSUE TITLE
Getting several warnings and an error when trying to create a new reaction message.

### ISSUE THREAD

**Issue by Su13n** [eibex/reaction-light#54]
**Describe the problem you are running into**

Mentioning the channel where I want to create the new reaction message causes several warning and an the attribute error to appear.

**Server:**

- OS: Ubuntu 18.04.5
- Python version: 3.8.7
- discord.py version: 1.6.0

**Traceback**

```
Reaction Light ready!
bot.py:415: RuntimeWarning: coroutine 'getchannel' was never awaited
  bot_permissions = await getchannel(target_channel).permissions_for(
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Ignoring exception in on_message
Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 415, in on_message
    bot_permissions = await getchannel(target_channel).permissions_for(
AttributeError: 'coroutine' object has no attribute 'permissions_for'
```

**Comment by eibex** [comment]
Thanks for the bug report, this should now be fixed in the latest version. You should be able to run `rl!update` without errors and get 2.1.3 running.
